language: generic
env:
  global:
    - IDE_VERSION=1.8.9
    - REPO_NAME=M5Stack-SD-Updater
    - SDAPP_FOLDER=$PWD/examples/M5Stack-SD-Menu/SD-Apps
    #- TRAVIS_TAG="v0.4.1"
    - M5_SD_BUILD_DIR=$TRAVIS_BUILD_DIR/build/SD-Content
  matrix:
    - EXAMPLE="M5Stack-SD-Menu" BOARD="esp32:esp32:m5stack-core-esp32:FlashFreq=80" ARCHIVE_ZIP="SD-Apps-Folder.zip"
    - EXAMPLE="M5Stack-SD-Menu" BOARD="esp32:esp32:odroid_esp32:FlashFreq=80" ARCHIVE_ZIP="SD-Apps-Folder-odroid.zip"  
#    - EXAMPLE="M5Stack-SDLoader-Snippet" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
before_install:
  - source $SDAPP_FOLDER/before_install.sh
  
install:
  - source $SDAPP_FOLDER/install.sh
  
script:
  - source $SDAPP_FOLDER/script.sh

before_deploy:
  - source $SDAPP_FOLDER/before_deploy.sh
    
after_deploy:
  - source $SDAPP_FOLDER/after_deploy.sh

deploy:
#  - provider: script
#    script: deploy_production.sh
#    on:
#      branch: production
#  - provider: script
#    script: deploy_staging.sh
#    on:
#      branch: staging
  provider: releases
  api_key: $GH_TOKEN
  overwrite: true
  skip_cleanup: true
  prerelease: $prerelease
  #target_commitish: $(git rev-list -n 1 $git_version)
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  name: SD-Updater-autorelease $TRAVIS_TAG
  body: Automated release from Travis CI (prerelease=$prerelease)
  #body: "compare: $(git rev-list -n 1 $git_version_last)...$(git rev-list -n 1 $git_version)"
  #draft: true
  file_glob: true
  file: 
    - $TRAVIS_BUILD_DIR/$ARCHIVE_ZIP
  #  - $TRAVIS_BUILD_DIR/$REPO_NAME.zip
  #file: $TRAVIS_BUILD_DIR/SD-Apps-Folder.zip
  on:
    #tags: true
    #branch: master
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|unstable$
    
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d1ffb10865e412333a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#branches:
#  except:
#    - /[0-9]+\.[0-9]+\.[0-9]+$/

