language: generic
env:
  global:
    - IDE_VERSION=1.8.9
    - REPO_NAME=M5Stack-SD-Updater
    - SDAPP_FOLDER=$PWD/examples/M5Stack-SD-Menu/SD-Apps
    #- TRAVIS_TAG="v0.4.1"
    - M5_SD_BUILD_DIR=$TRAVIS_BUILD_DIR/build/SD-Content
    - REMOTE_URL=https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG
  matrix:
    - EXAMPLE="M5Stack-SD-Menu" BOARD="esp32:esp32:m5stack-core-esp32:FlashFreq=80" ARCHIVE_ZIP="SD-Apps-Folder.zip"
    - EXAMPLE="M5Stack-SD-Menu" BOARD="esp32:esp32:odroid_esp32:FlashFreq=80" ARCHIVE_ZIP="SD-Apps-Folder-odroid.zip"  
#    - EXAMPLE="M5Stack-SDLoader-Snippet" BOARD="espressif:esp32:m5stack-core-esp32:FlashFreq=80"
before_install:
  - source $SDAPP_FOLDER/before_install.sh
  
install:
  - source $SDAPP_FOLDER/install.sh
  
script:
  - source $SDAPP_FOLDER/script.sh

before_deploy:
  - source $SDAPP_FOLDER/before_deploy.sh
    
after_deploy:
  - source $SDAPP_FOLDER/after_deploy.sh

deploy:
  - provider: releases
    on:
      branch: unstable
      tags: false
    api_key: $GH_TOKEN
    overwrite: true
    skip_cleanup: true
    prerelease: true # $prerelease
    target_commitish: $TRAVIS_COMMIT
    tag_name: $TRAVIS_TAG
    name: SD-Updater-autorelease $TRAVIS_TAG
    body: Automated Unstable release from Travis CI (prerelease=$prerelease)
    file:
      - $TRAVIS_BUILD_DIR/$ARCHIVE_ZIP
    file_glob: true

  - provider: releases
    on:
      branch: master
      tags: true
    api_key: $GH_TOKEN
    overwrite: true
    skip_cleanup: true
    prerelease: true # $prerelease
    target_commitish: $TRAVIS_COMMIT
    tag_name: $TRAVIS_TAG
    name: SD-Updater-autorelease $TRAVIS_TAG
    body: Automated Stable release from Travis CI (prerelease=$prerelease)
    file: 
      - $TRAVIS_BUILD_DIR/$ARCHIVE_ZIP
    file_glob: true
      
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2d1ffb10865e412333a9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

#branches:
#  except:
#    - /[0-9]+\.[0-9]+\.[0-9]+$/

